// Types
export type DashboardPageKeys = 'DASHBOARD' | 'INVENTORY' | 'ACCOUNT' | 'UPDATE_ACCOUNT' | 'ADD_PRODUCT' | 'PRODUCT_DETAILS';

// Mappings
export const DASHBOARD_PAGES: Record<DashboardPageKeys, string> = {
    DASHBOARD: 'DASHBOARD',
    INVENTORY: 'INVENTORY',
    ACCOUNT: 'ACCOUNT',
    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    PRODUCT_DETAILS: 'PRODUCT_DETAILS',
}